version: "3.9"

services:
  web:
    build: ./web
    ports:
      - "3000:3000"
    depends_on:
      - api
      - db
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: myapp
    volumes:
      - ./web:/app
      - ./web/node_modules:/app/node_modules

  api:
    build: ./api
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: myapp
    volumes:
      - ./api:/app
      - ./api/node_modules:/app/node_modules

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: PWD4toor
      MYSQL_DATABASE: test
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
