version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

  # backend:
  #   build: .
  #   command: 
  #     # - 
  #   ports:
  #     - "3001:3000"
  #   depends_on:
  #     - db

  frontend:
    build: ./frontend
    ports:
      - "3002:3000"
    volumes:
      - ./frontend/node_modules:/app/node_modules
      - ./frontend/build:/app/build
    # depends_on:
    #   - backend
